[workspace]
resolver = "2"
members = [
    "gaia-stub",
    "structpack",
    "gaia-tmtc",
    "gaia-ccsds-c2a",
    "tmtc-c2a",
]

[workspace.package]
version = "0.6.0"

[workspace.dependencies]
structpack = "0.5.0"

gaia-stub = { path = "gaia-stub" }
gaia-ccsds-c2a = { path = "gaia-ccsds-c2a" }
gaia-tmtc = { path = "gaia-tmtc" }
