[workspace]
resolver = "2"
members = [
    "gaia-stub",
    "structpack",
    "gaia-tmtc",
    "gaia-ccsds-c2a",
    "tmtc-c2a",
    "devtools-frontend"
]

[workspace.package]
version = "0.6.1"

[workspace.dependencies]
structpack = "0.6"

gaia-stub = { path = "gaia-stub" }
gaia-ccsds-c2a = { path = "gaia-ccsds-c2a" }
gaia-tmtc = { path = "gaia-tmtc" }
c2a-devtools-frontend = { path = "devtools-frontend" }
