accepted = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "OpenSSL",
]

workarounds = [
    "ring",
    "rustls",
    "tonic",
    "sentry",
    "prost",
    "chrono",
    "bitvec",
]
