[package]
name = "gaia-stub"
version = "0.5.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.10"
prost = "0.12"
prost-types = "0.12"

[build-dependencies]
tonic-build = "0.10"
