name: DevTools

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  devtools:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 21

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}

      - name: cache dependencies
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8

      - name: Install wasm-pack
        run: cargo install wasm-pack --locked

      - name: install pnpm
        working-directory: devtools-frontend
        run: corepack enable

      - name: install frontend dependencies
        working-directory: devtools-frontend
        run: pnpm install

      - name: lint
        working-directory: devtools-frontend
        run: pnpm lint

      - name: build
        working-directory: devtools-frontend
        run: pnpm build
