name: Release

on:
  push:
    branches:
      - main
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # for devtools-frontend
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 21

      - name: install apt depenedencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Rust toolchain
        id: toolchain
        working-directory: .
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8

      - name: install cargo-about
        run: |
          cargo install --locked cargo-about@0.6.4

      - name: Install wasm-pack
        run: |
          cargo install --locked wasm-pack

      - name: Build binaries
        run: |
          cargo build --target=${{ matrix.target }} --release --locked

      - name: Rename binaries
        run: |
          mkdir bin
          gaia_bins=("tmtc-c2a")
          for b in "${gaia_bins[@]}" ; do
            cp "./target/${{ matrix.target }}/release/${b}" "./bin/${b}-${{ matrix.target }}"
          done
          ls -lh ./bin

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: release-executable-${{ matrix.target }}
          if-no-files-found: error
          path: ./bin/

  package:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: install apt depenedencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Rust toolchain
        id: toolchain
        working-directory: .
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8

      - name: install cargo-about
        run: |
          cargo install --locked cargo-about@0.6.4

      - name: Install wasm-pack
        run: |
          cargo install --locked wasm-pack

      - name: package
        run: |
          cargo package

      # TODO: cargo publish

  release:
    name: Release
    needs: [ build, package ]
    permissions:
      contents: write

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          pattern: release-executable-*
          merge-multiple: true

      - run: |
          chmod +x tmtc-c2a*

      - run: ls -lh

      - name: Release to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            tmtc-c2a*
