name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      # for devtools-frontend
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 21

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy, rustfmt

      - name: cache dependencies
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8

      - name: Install cargo-about
        run: cargo install cargo-about@0.6.4 --locked

      - name: Install wasm-pack
        run: cargo install wasm-pack --locked

      - name: reviewdog / clippy
        uses: sksat/action-clippy@87e08e0c289f2654fe702b0aaf88c2f1027a3e57 # v1.1.1
        with:
          reporter: github-pr-review
          clippy_flags: --locked

      - name: format
        run: |
          cargo fmt --all -- --check

      - name: unit test
        run: |
          cargo test --locked
